# coding: utf-8

"""
    Onfido API v3.6

    The Onfido API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from onfido.models.document_breakdown_issuing_authority_breakdown_nfc_active_authentication import DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication
from onfido.models.document_breakdown_issuing_authority_breakdown_nfc_passive_authentication import DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication
from typing import Optional, Set
from typing_extensions import Self

class DocumentBreakdownIssuingAuthorityBreakdown(BaseModel):
    """
    DocumentBreakdownIssuingAuthorityBreakdown
    """ # noqa: E501
    nfc_active_authentication: Optional[DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication] = None
    nfc_passive_authentication: Optional[DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["nfc_active_authentication", "nfc_passive_authentication"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentBreakdownIssuingAuthorityBreakdown from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of nfc_active_authentication
        if self.nfc_active_authentication:
            _dict['nfc_active_authentication'] = self.nfc_active_authentication.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nfc_passive_authentication
        if self.nfc_passive_authentication:
            _dict['nfc_passive_authentication'] = self.nfc_passive_authentication.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentBreakdownIssuingAuthorityBreakdown from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nfc_active_authentication": DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication.from_dict(obj["nfc_active_authentication"]) if obj.get("nfc_active_authentication") is not None else None,
            "nfc_passive_authentication": DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication.from_dict(obj["nfc_passive_authentication"]) if obj.get("nfc_passive_authentication") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


