# coding: utf-8

"""
    Onfido API v3.6

    The Onfido API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from onfido.models.document_breakdown_data_comparison_breakdown_issuing_country import DocumentBreakdownDataComparisonBreakdownIssuingCountry
from typing import Optional, Set
from typing_extensions import Self

class DocumentBreakdownDataComparisonBreakdown(BaseModel):
    """
    DocumentBreakdownDataComparisonBreakdown
    """ # noqa: E501
    issuing_country: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    gender: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    date_of_expiry: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    last_name: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    document_type: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    document_numbers: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    first_name: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    date_of_birth: Optional[DocumentBreakdownDataComparisonBreakdownIssuingCountry] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["issuing_country", "gender", "date_of_expiry", "last_name", "document_type", "document_numbers", "first_name", "date_of_birth"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentBreakdownDataComparisonBreakdown from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of issuing_country
        if self.issuing_country:
            _dict['issuing_country'] = self.issuing_country.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gender
        if self.gender:
            _dict['gender'] = self.gender.to_dict()
        # override the default output from pydantic by calling `to_dict()` of date_of_expiry
        if self.date_of_expiry:
            _dict['date_of_expiry'] = self.date_of_expiry.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_name
        if self.last_name:
            _dict['last_name'] = self.last_name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of document_type
        if self.document_type:
            _dict['document_type'] = self.document_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of document_numbers
        if self.document_numbers:
            _dict['document_numbers'] = self.document_numbers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of first_name
        if self.first_name:
            _dict['first_name'] = self.first_name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of date_of_birth
        if self.date_of_birth:
            _dict['date_of_birth'] = self.date_of_birth.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentBreakdownDataComparisonBreakdown from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "issuing_country": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["issuing_country"]) if obj.get("issuing_country") is not None else None,
            "gender": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["gender"]) if obj.get("gender") is not None else None,
            "date_of_expiry": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["date_of_expiry"]) if obj.get("date_of_expiry") is not None else None,
            "last_name": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["last_name"]) if obj.get("last_name") is not None else None,
            "document_type": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["document_type"]) if obj.get("document_type") is not None else None,
            "document_numbers": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["document_numbers"]) if obj.get("document_numbers") is not None else None,
            "first_name": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["first_name"]) if obj.get("first_name") is not None else None,
            "date_of_birth": DocumentBreakdownDataComparisonBreakdownIssuingCountry.from_dict(obj["date_of_birth"]) if obj.get("date_of_birth") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


