# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from onfido.models.idr_ssn_breakdown_breakdown_full_match import IdrSsnBreakdownBreakdownFullMatch
from onfido.models.idr_ssn_breakdown_breakdown_last4_digits_match import IdrSsnBreakdownBreakdownLast4DigitsMatch
from typing import Optional, Set
from typing_extensions import Self

class IdrSsnBreakdownBreakdown(BaseModel):
    """
    IdrSsnBreakdownBreakdown
    """ # noqa: E501
    last_4_digits_match: Optional[IdrSsnBreakdownBreakdownLast4DigitsMatch] = None
    full_match: Optional[IdrSsnBreakdownBreakdownFullMatch] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["last_4_digits_match", "full_match"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdrSsnBreakdownBreakdown from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_4_digits_match
        if self.last_4_digits_match:
            _dict['last_4_digits_match'] = self.last_4_digits_match.to_dict()
        # override the default output from pydantic by calling `to_dict()` of full_match
        if self.full_match:
            _dict['full_match'] = self.full_match.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdrSsnBreakdownBreakdown from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "last_4_digits_match": IdrSsnBreakdownBreakdownLast4DigitsMatch.from_dict(obj["last_4_digits_match"]) if obj.get("last_4_digits_match") is not None else None,
            "full_match": IdrSsnBreakdownBreakdownFullMatch.from_dict(obj["full_match"]) if obj.get("full_match") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


