# coding: utf-8

"""
    Onfido API v3.6

    The Onfido API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReportStatus(str, Enum):
    """
    The current state of the report in the checking process. Read-only.
    """

    """
    allowed enum values
    """
    AWAITING_DATA = 'awaiting_data'
    AWAITING_APPROVAL = 'awaiting_approval'
    CANCELLED = 'cancelled'
    COMPLETE = 'complete'
    WITHDRAWN = 'withdrawn'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReportStatus from a JSON string"""
        return cls(json.loads(json_str))


