# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onfido.models.lists import Lists
from onfido.models.media import Media
from onfido.models.pep import Pep
from onfido.models.sanctions import Sanctions
from typing import Optional, Set
from typing_extensions import Self

class RiskIndicators(BaseModel):
    """
    RiskIndicators
    """ # noqa: E501
    aml_types: Optional[List[StrictStr]] = None
    lists: Optional[List[Lists]] = None
    media: Optional[List[Media]] = None
    peps: Optional[List[Pep]] = None
    sanctions: Optional[List[Sanctions]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["aml_types", "lists", "media", "peps", "sanctions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskIndicators from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in lists (list)
        _items = []
        if self.lists:
            for _item_lists in self.lists:
                if _item_lists:
                    _items.append(_item_lists.to_dict())
            _dict['lists'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in media (list)
        _items = []
        if self.media:
            for _item_media in self.media:
                if _item_media:
                    _items.append(_item_media.to_dict())
            _dict['media'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in peps (list)
        _items = []
        if self.peps:
            for _item_peps in self.peps:
                if _item_peps:
                    _items.append(_item_peps.to_dict())
            _dict['peps'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sanctions (list)
        _items = []
        if self.sanctions:
            for _item_sanctions in self.sanctions:
                if _item_sanctions:
                    _items.append(_item_sanctions.to_dict())
            _dict['sanctions'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if aml_types (nullable) is None
        # and model_fields_set contains the field
        if self.aml_types is None and "aml_types" in self.model_fields_set:
            _dict['aml_types'] = None

        # set to None if lists (nullable) is None
        # and model_fields_set contains the field
        if self.lists is None and "lists" in self.model_fields_set:
            _dict['lists'] = None

        # set to None if media (nullable) is None
        # and model_fields_set contains the field
        if self.media is None and "media" in self.model_fields_set:
            _dict['media'] = None

        # set to None if peps (nullable) is None
        # and model_fields_set contains the field
        if self.peps is None and "peps" in self.model_fields_set:
            _dict['peps'] = None

        # set to None if sanctions (nullable) is None
        # and model_fields_set contains the field
        if self.sanctions is None and "sanctions" in self.model_fields_set:
            _dict['sanctions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskIndicators from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aml_types": obj.get("aml_types"),
            "lists": [Lists.from_dict(_item) for _item in obj["lists"]] if obj.get("lists") is not None else None,
            "media": [Media.from_dict(_item) for _item in obj["media"]] if obj.get("media") is not None else None,
            "peps": [Pep.from_dict(_item) for _item in obj["peps"]] if obj.get("peps") is not None else None,
            "sanctions": [Sanctions.from_dict(_item) for _item in obj["sanctions"]] if obj.get("sanctions") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


