# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RiskDecision(str, Enum):
    """
    RiskDecision
    """

    """
    allowed enum values
    """
    NOT_REVIEWED = 'NOT_REVIEWED'
    IN_REVIEW = 'IN_REVIEW'
    FALSE_POSITIVE = 'FALSE_POSITIVE'
    TRUE_POSITIVE = 'TRUE_POSITIVE'
    UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RiskDecision from a JSON string"""
        return cls(json.loads(json_str))


