# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from onfido.models.watchlist_mesh_person import WatchlistMeshPerson
from onfido.models.watchlist_mesh_risk_indicators import WatchlistMeshRiskIndicators
from typing import Optional, Set
from typing_extensions import Self

class WatchlistMeshProfile(BaseModel):
    """
    WatchlistMeshProfile
    """ # noqa: E501
    identifier: Optional[StrictStr] = None
    match_types: Optional[List[StrictStr]] = None
    match_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The match score assigned to the profile.")
    matching_name: Optional[StrictStr] = None
    person: Optional[WatchlistMeshPerson] = None
    risk_indicators: Optional[WatchlistMeshRiskIndicators] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["identifier", "match_types", "match_score", "matching_name", "person", "risk_indicators"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WatchlistMeshProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of person
        if self.person:
            _dict['person'] = self.person.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risk_indicators
        if self.risk_indicators:
            _dict['risk_indicators'] = self.risk_indicators.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if identifier (nullable) is None
        # and model_fields_set contains the field
        if self.identifier is None and "identifier" in self.model_fields_set:
            _dict['identifier'] = None

        # set to None if match_types (nullable) is None
        # and model_fields_set contains the field
        if self.match_types is None and "match_types" in self.model_fields_set:
            _dict['match_types'] = None

        # set to None if matching_name (nullable) is None
        # and model_fields_set contains the field
        if self.matching_name is None and "matching_name" in self.model_fields_set:
            _dict['matching_name'] = None

        # set to None if person (nullable) is None
        # and model_fields_set contains the field
        if self.person is None and "person" in self.model_fields_set:
            _dict['person'] = None

        # set to None if risk_indicators (nullable) is None
        # and model_fields_set contains the field
        if self.risk_indicators is None and "risk_indicators" in self.model_fields_set:
            _dict['risk_indicators'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WatchlistMeshProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": obj.get("identifier"),
            "match_types": obj.get("match_types"),
            "match_score": obj.get("match_score"),
            "matching_name": obj.get("matching_name"),
            "person": WatchlistMeshPerson.from_dict(obj["person"]) if obj.get("person") is not None else None,
            "risk_indicators": WatchlistMeshRiskIndicators.from_dict(obj["risk_indicators"]) if obj.get("risk_indicators") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


