# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onfido.models.risk_decision import RiskDecision
from onfido.models.risk_detail import RiskDetail
from typing import Optional, Set
from typing_extensions import Self

class WatchlistAlertRisk(BaseModel):
    """
    WatchlistAlertRisk
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, description="The date and time at which the risk record was created.")
    decision: Optional[RiskDecision] = Field(default=None, description="The review decision currently applied to the risk.")
    previous_decision: Optional[RiskDecision] = Field(default=None, description="The previous review decision, if one exists.")
    detail: Optional[RiskDetail] = Field(default=None, description="Additional details about the risk.")
    identifier: Optional[StrictStr] = Field(default=None, description="The unique identifier of the risk record.")
    type: Optional[StrictStr] = Field(default=None, description="The type of risk returned for the alert.")
    updated_by: Optional[StrictStr] = Field(default=None, description="The identifier of the user or system that last updated the risk decision.")
    updated_at: Optional[datetime] = Field(default=None, description="The date and time at which the risk record was last updated.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["created_at", "decision", "previous_decision", "detail", "identifier", "type", "updated_by", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WatchlistAlertRisk from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of detail
        if self.detail:
            _dict['detail'] = self.detail.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if previous_decision (nullable) is None
        # and model_fields_set contains the field
        if self.previous_decision is None and "previous_decision" in self.model_fields_set:
            _dict['previous_decision'] = None

        # set to None if updated_by (nullable) is None
        # and model_fields_set contains the field
        if self.updated_by is None and "updated_by" in self.model_fields_set:
            _dict['updated_by'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WatchlistAlertRisk from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "decision": obj.get("decision"),
            "previous_decision": obj.get("previous_decision"),
            "detail": RiskDetail.from_dict(obj["detail"]) if obj.get("detail") is not None else None,
            "identifier": obj.get("identifier"),
            "type": obj.get("type"),
            "updated_by": obj.get("updated_by"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


