# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onfido.models.watchlist_mesh_associate import WatchlistMeshAssociate
from onfido.models.watchlist_mesh_date_value import WatchlistMeshDateValue
from onfido.models.watchlist_mesh_image import WatchlistMeshImage
from onfido.models.watchlist_mesh_name import WatchlistMeshName
from typing import Optional, Set
from typing_extensions import Self

class WatchlistMeshPerson(BaseModel):
    """
    WatchlistMeshPerson
    """ # noqa: E501
    associates: Optional[List[WatchlistMeshAssociate]] = None
    dates_of_birth: Optional[List[WatchlistMeshDateValue]] = None
    dates_of_death: Optional[List[WatchlistMeshDateValue]] = None
    images: Optional[List[WatchlistMeshImage]] = None
    names: Optional[List[WatchlistMeshName]] = None
    places_of_birth: Optional[List[StrictStr]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["associates", "dates_of_birth", "dates_of_death", "images", "names", "places_of_birth"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WatchlistMeshPerson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in associates (list)
        _items = []
        if self.associates:
            for _item_associates in self.associates:
                if _item_associates:
                    _items.append(_item_associates.to_dict())
            _dict['associates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in dates_of_birth (list)
        _items = []
        if self.dates_of_birth:
            for _item_dates_of_birth in self.dates_of_birth:
                if _item_dates_of_birth:
                    _items.append(_item_dates_of_birth.to_dict())
            _dict['dates_of_birth'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in dates_of_death (list)
        _items = []
        if self.dates_of_death:
            for _item_dates_of_death in self.dates_of_death:
                if _item_dates_of_death:
                    _items.append(_item_dates_of_death.to_dict())
            _dict['dates_of_death'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in images (list)
        _items = []
        if self.images:
            for _item_images in self.images:
                if _item_images:
                    _items.append(_item_images.to_dict())
            _dict['images'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in names (list)
        _items = []
        if self.names:
            for _item_names in self.names:
                if _item_names:
                    _items.append(_item_names.to_dict())
            _dict['names'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if associates (nullable) is None
        # and model_fields_set contains the field
        if self.associates is None and "associates" in self.model_fields_set:
            _dict['associates'] = None

        # set to None if dates_of_birth (nullable) is None
        # and model_fields_set contains the field
        if self.dates_of_birth is None and "dates_of_birth" in self.model_fields_set:
            _dict['dates_of_birth'] = None

        # set to None if dates_of_death (nullable) is None
        # and model_fields_set contains the field
        if self.dates_of_death is None and "dates_of_death" in self.model_fields_set:
            _dict['dates_of_death'] = None

        # set to None if images (nullable) is None
        # and model_fields_set contains the field
        if self.images is None and "images" in self.model_fields_set:
            _dict['images'] = None

        # set to None if names (nullable) is None
        # and model_fields_set contains the field
        if self.names is None and "names" in self.model_fields_set:
            _dict['names'] = None

        # set to None if places_of_birth (nullable) is None
        # and model_fields_set contains the field
        if self.places_of_birth is None and "places_of_birth" in self.model_fields_set:
            _dict['places_of_birth'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WatchlistMeshPerson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "associates": [WatchlistMeshAssociate.from_dict(_item) for _item in obj["associates"]] if obj.get("associates") is not None else None,
            "dates_of_birth": [WatchlistMeshDateValue.from_dict(_item) for _item in obj["dates_of_birth"]] if obj.get("dates_of_birth") is not None else None,
            "dates_of_death": [WatchlistMeshDateValue.from_dict(_item) for _item in obj["dates_of_death"]] if obj.get("dates_of_death") is not None else None,
            "images": [WatchlistMeshImage.from_dict(_item) for _item in obj["images"]] if obj.get("images") is not None else None,
            "names": [WatchlistMeshName.from_dict(_item) for _item in obj["names"]] if obj.get("names") is not None else None,
            "places_of_birth": obj.get("places_of_birth")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


