# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from onfido.models.watchlist_mesh_added_mentions import WatchlistMeshAddedMentions
from onfido.models.watchlist_mesh_profile import WatchlistMeshProfile
from typing import Optional, Set
from typing_extensions import Self

class WatchlistMeshRiskDetail(BaseModel):
    """
    WatchlistMeshRiskDetail
    """ # noqa: E501
    change_type: Optional[StrictStr] = Field(default=None, description="The type of change that triggered the risk, if available.")
    configuration_identifier: Optional[UUID] = Field(default=None, description="The identifier of the screening configuration associated with the risk.")
    profile: Optional[WatchlistMeshProfile] = Field(default=None, description="The matched profile associated with the risk.")
    added_mentions: Optional[WatchlistMeshAddedMentions] = Field(default=None, description="Newly added mentions associated with the risk.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["change_type", "configuration_identifier", "profile", "added_mentions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WatchlistMeshRiskDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of profile
        if self.profile:
            _dict['profile'] = self.profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of added_mentions
        if self.added_mentions:
            _dict['added_mentions'] = self.added_mentions.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if change_type (nullable) is None
        # and model_fields_set contains the field
        if self.change_type is None and "change_type" in self.model_fields_set:
            _dict['change_type'] = None

        # set to None if configuration_identifier (nullable) is None
        # and model_fields_set contains the field
        if self.configuration_identifier is None and "configuration_identifier" in self.model_fields_set:
            _dict['configuration_identifier'] = None

        # set to None if profile (nullable) is None
        # and model_fields_set contains the field
        if self.profile is None and "profile" in self.model_fields_set:
            _dict['profile'] = None

        # set to None if added_mentions (nullable) is None
        # and model_fields_set contains the field
        if self.added_mentions is None and "added_mentions" in self.model_fields_set:
            _dict['added_mentions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WatchlistMeshRiskDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "change_type": obj.get("change_type"),
            "configuration_identifier": obj.get("configuration_identifier"),
            "profile": WatchlistMeshProfile.from_dict(obj["profile"]) if obj.get("profile") is not None else None,
            "added_mentions": WatchlistMeshAddedMentions.from_dict(obj["added_mentions"]) if obj.get("added_mentions") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


