# coding: utf-8

"""
    Onfido Public API v3.6

    The Onfido Public API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from onfido.models.watchlist_mesh_field import WatchlistMeshField
from typing import Optional, Set
from typing_extensions import Self

class WatchlistMeshLists(BaseModel):
    """
    WatchlistMeshLists
    """ # noqa: E501
    aml_types: Optional[List[StrictStr]] = None
    country_codes: Optional[List[StrictStr]] = None
    fields: Optional[List[WatchlistMeshField]] = None
    identifier: Optional[StrictStr] = None
    listing_ended_utc: Optional[StrictStr] = None
    listing_started_utc: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    related_urls: Optional[List[StrictStr]] = None
    url: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["aml_types", "country_codes", "fields", "identifier", "listing_ended_utc", "listing_started_utc", "name", "related_urls", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WatchlistMeshLists from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict['fields'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if aml_types (nullable) is None
        # and model_fields_set contains the field
        if self.aml_types is None and "aml_types" in self.model_fields_set:
            _dict['aml_types'] = None

        # set to None if country_codes (nullable) is None
        # and model_fields_set contains the field
        if self.country_codes is None and "country_codes" in self.model_fields_set:
            _dict['country_codes'] = None

        # set to None if fields (nullable) is None
        # and model_fields_set contains the field
        if self.fields is None and "fields" in self.model_fields_set:
            _dict['fields'] = None

        # set to None if identifier (nullable) is None
        # and model_fields_set contains the field
        if self.identifier is None and "identifier" in self.model_fields_set:
            _dict['identifier'] = None

        # set to None if listing_ended_utc (nullable) is None
        # and model_fields_set contains the field
        if self.listing_ended_utc is None and "listing_ended_utc" in self.model_fields_set:
            _dict['listing_ended_utc'] = None

        # set to None if listing_started_utc (nullable) is None
        # and model_fields_set contains the field
        if self.listing_started_utc is None and "listing_started_utc" in self.model_fields_set:
            _dict['listing_started_utc'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if related_urls (nullable) is None
        # and model_fields_set contains the field
        if self.related_urls is None and "related_urls" in self.model_fields_set:
            _dict['related_urls'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WatchlistMeshLists from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aml_types": obj.get("aml_types"),
            "country_codes": obj.get("country_codes"),
            "fields": [WatchlistMeshField.from_dict(_item) for _item in obj["fields"]] if obj.get("fields") is not None else None,
            "identifier": obj.get("identifier"),
            "listing_ended_utc": obj.get("listing_ended_utc"),
            "listing_started_utc": obj.get("listing_started_utc"),
            "name": obj.get("name"),
            "related_urls": obj.get("related_urls"),
            "url": obj.get("url")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


