# coding: utf-8

"""
    Onfido API v3.6

    The Onfido API (v3.6)

    The version of the OpenAPI document: v3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WorkflowRunStatus(str, Enum):
    """
    WorkflowRunStatus
    """

    """
    allowed enum values
    """
    PROCESSING = 'processing'
    AWAITING_INPUT = 'awaiting_input'
    AWAITING_CLIENT_INPUT = 'awaiting_client_input'
    APPROVED = 'approved'
    DECLINED = 'declined'
    REVIEW = 'review'
    ABANDONED = 'abandoned'
    ERROR = 'error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkflowRunStatus from a JSON string"""
        return cls(json.loads(json_str))


